#!/bin/sh
##########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#                                   
# Copyright 2017 RDK Management                                                                   
#                                                                                                 
# Licensed under the Apache License, Version 2.0 (the "License");                               
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################


execute_component() {
	
case $1 in
	"ccsp-commonlib")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspCommonLibrary ccsp-commonlib
		cd ccsp-commonlib
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-commonlib/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-commonlib/image/usr --bindir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-commonlib/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-commonlib/image/com --localstatedir=/build-qemux86broadband/source/ccsp-commonlib/image/var --libdir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-commonlib/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-I /usr/include/dbus-1.0 -I /usr/lib/dbus-1.0/include"
		make install
	 ;;
	"ccsp-cr")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspCr ccsp-cr
		cd ccsp-cr
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-cr/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-cr/image/usr --bindir=/build-qemux86broadband/source/ccsp-cr/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-cr/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-cr/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-cr/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-cr/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-cr/image/com --localstatedir=/build-qemux86broadband/source/ccsp-cr/image/var --libdir=/build-qemux86broadband/source/ccsp-cr/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-cr/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-cr/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-cr/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-cr/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG -I=/usr/include/breakpad   -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunctio""n-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIA""N_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY         ""   -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_"" -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_         -I=/usr/include/dbus-1.0     -I=/usr/lib/dbus-1.0/include     -I=/usr/include/ccsp     " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers /usr/lib/libpthread.so /usr/lib/libdl.so -lstdc++" 
		make install
	;;
	"ccsp-psm")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspPsm ccsp-psm
		cd ccsp-psm
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-psm/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-psm/image/usr --bindir=/build-qemux86broadband/source/ccsp-psm/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-psm/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-psm/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-psm/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-psm/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-psm/image/com --localstatedir=/build-qemux86broadband/source/ccsp-psm/image/var --libdir=/build-qemux86broadband/source/ccsp-psm/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-psm/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-psm/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-psm/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-psm/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		cp -fr source-pc/ssp_HAL_apis.c source/Ssp/psm_hal_apis.c
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG -I=/usr/include/breakpad   -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_         -I=/usr/include/dbus-1.0     -I=/usr/lib/dbus-1.0/include     -I=/usr/include/ccsp     " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers  /usr/lib/libpthread.so -lstdc++     -ldbus-1   /usr/lib/libdl.so  " 
		make install
	;;
	"ccsp-p-and-m")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspPandM ccsp-p-and-m
		cd ccsp-p-and-m
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-p-and-m/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-p-and-m/image/usr --bindir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-p-and-m/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-p-and-m/image/com --localstatedir=/build-qemux86broadband/source/ccsp-p-and-m/image/var --libdir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-p-and-m/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-platform=pc --with-ccsp-arch=pc
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG  -I=/usr/include/breakpad   -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunctio""n-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIA""N_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY         ""   -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_"" -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_  -DCONFIG_VENDOR_CUSTOMER_COMCAST -DCONFIG_INTERNET2.0 -DCONFIG_CISCO_HOTSPOT -I=/usr/include/dbus-1.0     -I=/usr/lib/dbus-1.0/include -I/usr/include/ccsp -I/usr/include/utctx -I/usr/include/utapi -I/usr/include/syscfg " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers  /usr/lib/libpthread.so -lstdc++     -ldbus-1     -lutctx     -lutapi          -lhal_m""somgmt     -lapi_dhcpv4c     -lfirewall_hal     -lhal_vlan     -lsyscfg     -lhal_platform  -llmapi /usr/lib/libdl.so -ltr181   "
		make install
	 ;;
	"ccsp-wifi-agent")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspWifiAgent ccsp-wifi-agent
		cd ccsp-wifi-agent
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr --bindir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-wifi-agent/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-wifi-agent/image/com --localstatedir=/build-qemux86broadband/source/ccsp-wifi-agent/image/var --libdir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-wifi-agent/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-platform=pc --with-ccsp-arch=pc
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG -I=/usr/include/breakpad   -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_         -I/usr/include/dbus-1.0     -I/usr/lib/dbus-1.0/include     -I/usr/include/ccsp      " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers  /usr/lib/libpthread.so -lstdc++     -ldbus-1          -lhal_wifi   /usr/lib/libdl.so  "
		make install
	 ;;
	"ccsp-lm-lite")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspLMLite ccsp-lm-lite
		cd ccsp-lm-lite
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-lm-lite/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-lm-lite/image/usr --bindir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-lm-lite/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-lm-lite/image/com --localstatedir=/build-qemux86broadband/source/ccsp-lm-lite/image/var --libdir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-lm-lite/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-platform=pc --with-ccsp-arch=pc
		make liblmapi.la
		make all CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -DFEATURE_SUPPORT_RDKLOG -I/usr/include/dbus-1.0 -I/usr/include/libxml2 -I/usr/lib/dbus-1.0/include -I/usr/include/ccsp -I/usr/include/mlt -I/usr/include/trower-base64 -I/usr/include/libparodus -I/usr/include/cimplog -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ARM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -DINCLUDE_BREAKPAD -DUSE_NOTIFY_COMPONENT -DNTPD_ENABLE -DUTC_ENABLE -DXDNS_ENABLE -DMOCA_HOME_ISOLATION -D_COSA_SIM_ -DFEATURE_SUPPORT_ONBOARD_LOGGING -D_RDK_REF_PLATFORM_" LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers -lbreakpadwrapper     -lcurl     -lxml2     -ldbus-1         -lsecure_wrapper  /usr/lib/libdl.so /usr/lib/libpthread.so      " 
		make install
	;;
	"ccsp-hotspot")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hotspot ccsp-hotspot
		cd ccsp-hotspot
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-hotspot/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-hotspot/image/usr --bindir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-hotspot/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-hotspot/image/com --localstatedir=/build-qemux86broadband/source/ccsp-hotspot/image/var --libdir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-hotspot/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-platform=pc --with-ccsp-arch=pc
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG     -I/usr/include/dbus-1.0    -I/usr/lib/dbus-1.0/include    -I/usr/include/ccsp      -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_    "  LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers /usr/lib/libpthread.so /usr/lib/libdl.so"
		make install
	;;
	"ccsp-snmp-pa")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspSnmpPa ccsp-snmp-pa
		cd ccsp-snmp-pa
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr --bindir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-snmp-pa/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-snmp-pa/image/com --localstatedir=/build-qemux86broadband/source/ccsp-snmp-pa/image/var --libdir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-snmp-pa/image/usr/share/man --disable-silent-rules --disable-dependency-tracking 
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG  -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_         -I=/usr/include/dbus-1.0     -I=/usr/lib/dbus-1.0/include     -I=/usr/include/ccsp     " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers     -ldbus-1   /usr/lib/libdl.so  "
		make install
	;;
	"ccsp-tr069-pa")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspTr069Pa ccsp-tr069-pa
		cd ccsp-tr069-pa
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr --bindir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-tr069-pa/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-tr069-pa/image/com --localstatedir=/build-qemux86broadband/source/ccsp-tr069-pa/image/var --libdir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-tr069-pa/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-arch=pc
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG -I=/usr/include/breakpad   -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_         -I=/usr/include/dbus-1.0     -I=/usr/lib/dbus-1.0/include     -I=/usr/include/ccsp     -I=/usr/include/syscfg     " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers  /usr/lib/libpthread.so -lstdc++     -ldbus-1    /usr/lib/libdl.so "
		make install
	;;
	"hal-wifi-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-wifi-generic
		cd hal-wifi-generic/source-pc/wifi
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr --exec_prefix=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr --bindir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/com --localstatedir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/var --libdir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/lib --includedir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/include --infodir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-wifi-generic/source-pc/wifi/image/usr/share/man --disable-silent-rules --disable-dependency-tracking 
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-dhcpv4c-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-dhcpv4c-generic
		cd hal-dhcpv4c-generic/source-pc/dhcpv4c
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr --exec_prefix=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr --bindir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/com --localstatedir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/var --libdir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/lib --includedir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/include --infodir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-dhcpv4c-generic/source-pc/dhcpv4c/image/usr/share/man --disable-silent-rules --disable-dependency-tracking 
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-platform-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-platform-generic
		cd hal-platform-generic/source-pc/platform
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr --exec_prefix=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr --bindir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/com --localstatedir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/var --libdir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/lib --includedir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/include --infodir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-platform-generic/source-pc/platform/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-moca-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-moca-generic
		cd hal-moca-generic/source-pc/moca
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr --exec_prefix=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr --bindir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/com --localstatedir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/var --libdir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/lib --includedir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/include --infodir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-moca-generic/source-pc/moca/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-ethsw-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-ethsw-generic
		cd hal-ethsw-generic/source-pc/ethsw
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr --exec_prefix=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr --bindir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/com --localstatedir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/var --libdir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/lib --includedir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/include --infodir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-ethsw-generic/source-pc/ethsw/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-firewall-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-firewall-generic
		cd hal-firewall-generic/source-pc/firewall
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr --exec_prefix=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr --bindir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/com --localstatedir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/var --libdir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/lib --includedir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/include --infodir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-firewall-generic/source-pc/firewall/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-mso_mgmt-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-mso_mgmt-generic
		cd hal-mso_mgmt-generic/source-pc/mso_mgmt
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr --exec_prefix=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr --bindir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/com --localstatedir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/var --libdir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/lib --includedir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/include --infodir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-mso_mgmt-generic/source-pc/mso_mgmt/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-cm-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-cm-generic
		cd hal-cm-generic/source-pc/cm
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr --exec_prefix=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr --bindir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/com --localstatedir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/var --libdir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/lib --includedir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/include --infodir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-cm-generic/source-pc/cm/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-vlan-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-vlan-generic
		cd hal-vlan-generic/source-pc/vlan
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr --exec_prefix=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr --bindir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/com --localstatedir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/var --libdir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/lib --includedir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/include --infodir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-vlan-generic/source-pc/vlan/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-Os -pipe -g -feliminate-unused-debug-types  -I=/usr/include/ccsp " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-mta-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-mta-generic
		cd hal-mta-generic/source-pc/mta
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr --exec_prefix=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr --bindir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/com --localstatedir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/var --libdir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/lib --includedir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/include --infodir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-mta-generic/source-pc/mta/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-pipe -g -feliminate-unused-debug-types -Os -pipe -I=/usr/include/ccsp" LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"hal-epon-generic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/hal hal-epon-generic
		cd hal-epon-generic/source/epon
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr --exec_prefix=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr --bindir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/bin --sbindir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/sbin --libexecdir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/libexec --datadir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/share --sysconfdir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/etc --sharedstatedir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/com --localstatedir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/var --libdir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/lib --includedir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/include --oldincludedir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/include --infodir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/share/info --mandir=/build-qemux86broadband/source/hal-epon-generic/source/epon/image/usr/share/man --disable-silent-rules --disable-dependency-tracking
		make CFLAGS="-pipe -g -feliminate-unused-debug-types -Os -pipe -I=/usr/include/ccsp" LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
		make install
	;;
	"utopia")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/Utopia utopia
		cd utopia
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/utopia/image/usr --exec_prefix=/build-qemux86broadband/source/utopia/image/usr --bindir=/build-qemux86broadband/source/utopia/image/usr/bin --sbindir=/build-qemux86broadband/source/utopia/image/usr/sbin --libexecdir=/build-qemux86broadband/source/utopia/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/utopia/image/usr/share --sysconfdir=/build-qemux86broadband/source/utopia/image/etc --sharedstatedir=/build-qemux86broadband/source/utopia/image/com --localstatedir=/build-qemux86broadband/source/utopia/image/var --libdir=/build-qemux86broadband/source/utopia/image/usr/lib --includedir=/build-qemux86broadband/source/utopia/image/usr/include --oldincludedir=/build-qemux86broadband/source/utopia/image/usr/include --infodir=/build-qemux86broadband/source/utopia/image/usr/share/info --mandir=/build-qemux86broadband/source/utopia/image/usr/share/man --disable-silent-rules --disable-dependency-tracking 
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG      -I/usr/include/ccsp     -DCONFIG_BUILD_TRIGGER      -I=/usr/include/breakpad   -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_      "  LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers  /usr/lib/libpthread.so -lstdc++ /usr/lib/libdl.so"
		make install
	;;
	"ccsp-webui")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/webui ccsp-webui
		cd ccsp-webui/source/CcspPhpExtension
		phpize
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/ccsp-webui/image/usr --exec_prefix=/build-qemux86broadband/source/ccsp-webui/image/usr --bindir=/build-qemux86broadband/source/ccsp-webui/image/usr/bin --sbindir=/build-qemux86broadband/source/ccsp-webui/image/usr/sbin --libexecdir=/build-qemux86broadband/source/ccsp-webui/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/ccsp-webui/image/usr/share --sysconfdir=/build-qemux86broadband/source/ccsp-webui/image/etc --sharedstatedir=/build-qemux86broadband/source/ccsp-webui/image/com --localstatedir=/build-qemux86broadband/source/ccsp-webui/image/var --libdir=/build-qemux86broadband/source/ccsp-webui/image/usr/lib --includedir=/build-qemux86broadband/source/ccsp-webui/image/usr/include --oldincludedir=/build-qemux86broadband/source/ccsp-webui/image/usr/include --infodir=/build-qemux86broadband/source/ccsp-webui/image/usr/share/info --mandir=/build-qemux86broadband/source/ccsp-webui/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --enable-cosa CCSP_COMMON_LIB=/usr/lib
		make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG      -I/usr/include/dbus-1.0     -I/usr/lib/dbus-1.0/include     -I/usr/include/ccsp  -I/usr/include/libsafec   -fPIC       -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_    " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers       -ldbus-1      /usr/lib/libdl.so"
		make install
	;;
	"TestandDiagnostic")
		git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/TestAndDiagnostic TestAndDiagnostic
		cd TestAndDiagnostic
		autoreconf -i
		./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/TestAndDiagnostic/image/usr --exec_prefix=/build-qemux86broadband/source/TestAndDiagnostic/image/usr --bindir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/bin --sbindir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/sbin --libexecdir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/share --sysconfdir=/build-qemux86broadband/source/TestAndDiagnostic/image/etc --sharedstatedir=/build-qemux86broadband/source/TestAndDiagnostic/image/com --localstatedir=/build-qemux86broadband/source/TestAndDiagnostic/image/var --libdir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/lib --includedir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/include --oldincludedir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/include --infodir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/share/info --mandir=/build-qemux86broadband/source/TestAndDiagnostic/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-arch=pc
		make CFLAGS="-pipe -g -feliminate-unused-debug-types -Os -pipe -DFEATURE_SUPPORT_RDKLOG -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT -DDUAL_CORE_XB3 -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_ -I/usr/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/ccsp -I/usr/include/utapi -I/usr/include/utctx -I/usr/include/ulog -I/usr/include/syscfg" LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -lrdkloggers     -ldbus-1 /usr/lib/libdl.so"
		make install
	;;
	"ccsp-dmcli")
                git clone https://code.rdkcentral.com/r/rdkb/components/opensource/ccsp/CcspDmCli CcspDmcli
                cd CcspDmcli
                autoreconf -i
                ./configure --build=i686-linux --host=i586-rdk-linux --target=i586-rdk-linux --prefix=/build-qemux86broadband/source/CcspDmcli/image/usr --exec_prefix=/build-qemux86broadband/source/CcspDmcli/image/usr --bindir=/build-qemux86broadband/source/CcspDmcli/image/usr/bin --sbindir=/build-qemux86broadband/source/CcspDmcli/image/usr/sbin --libexecdir=/build-qemux86broadband/source/CcspDmcli/image/usr/lib/ccsp-common-library --datadir=/build-qemux86broadband/source/CcspDmcli/image/usr/share --sysconfdir=/build-qemux86broadband/source/CcspDmcli/image/etc --sharedstatedir=/build-qemux86broadband/source/CcspDmcli/image/com --localstatedir=/build-qemux86broadband/source/CcspDmcli/image/var --libdir=/build-qemux86broadband/source/CcspDmcli/image/usr/lib --includedir=/build-qemux86broadband/source/CcspDmcli/image/usr/include --oldincludedir=/build-qemux86broadband/source/CcspDmcli/image/usr/include --infodir=/build-qemux86broadband/source/CcspDmcli/image/usr/share/info --mandir=/build-qemux86broadband/source/CcspDmcli/image/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-ccsp-arch=pc
                make CFLAGS=" -O2 -pipe -g -feliminate-unused-debug-types -DFEATURE_SUPPORT_RDKLOG -I/usr/include/dbus-1.0     -I/usr/lib/dbus-1.0/include     -I/usr/include/ccsp -I/usr/include/libsafec     -fPIC       -D_COSA_HAL_ -U_COSA_SIM_ -fno-exceptions -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-strict-aliasing            -DCONFIG_SYSTEM_MOCA -D_ANSC_LINUX -D_ANSC_USER -D_ANSC_LITTLE_ENDIAN_ -D_CCSP_CWMP_TCP_CONNREQ_HANDLER            -D_DSLH_STUN_ -D_NO_PKI_KB5_SUPPORT -D_BBHM_SSE_FILE_IO -D_ANSC_USE_OPENSSL_ -DENABLE_SA_KEY            -D_ANSC_AES_USED_ -D_COSA_INTEL_USG_ATOM_ -D_COSA_FOR_COMCAST_ -D_NO_EXECINFO_H_ -DFEATURE_SUPPORT_SYSLOG            -DBUILD_WEB -D_NO_ANSC_ZLIB_ -D_DEBUG -U_ANSC_IPV6_COMPATIBLE_ -D_ENABLE_BAND_STEERING_ -DUSE_NOTIFY_COMPONENT -D_BEACONRATE_SUPPORT            -DDUAL_CORE_XB3  -DUTC_ENABLE_ATOM -D_ATM_SUPPORT -D_COSA_SIM_    " LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -lrdkloggers       -ldbus-1  -lsafec-3.5    /usr/lib/libdl.so"
                make install
        ;;
esac 	
}
echo "====================================================="
echo "********* List of ccsp-components are ***************"
echo "             1.ccsp-commonlib                        "
echo "             2.ccsp-cr                               "
echo "             3.ccsp-psm                              "
echo "             4.ccsp-p-and-m                          "               
echo "             5.ccsp-wifi-agent                       "
echo "             6.ccsp-lm-lite                          "
echo "             7.ccsp-hotspot                          "
echo "             8.ccsp-snmp-pa                          "
echo "             9.ccsp-tr069-pa                         "
echo "             10.hal-wifi-generic                     "
echo "             11.hal-dhcpv4c-generic                  "
echo "             12.hal-platform-generic                 "
echo "             13.hal-moca-generic                     "
echo "             14.hal-ethsw-generic                    "
echo "             15.hal-firewall-generic                 "
echo "             16.hal-mso_mgmt-generic                 "
echo "             17.hal-cm-generic                       "
echo "             18.hal-vlan-generic                     "
echo "             19.hal-mta-generic                      "
echo "             20.hal-epon-generic                     "
echo "             21.utopia                               "
echo "             22.ccsp-webui                           "
echo "             23.TestandDiagnostic                    "
echo "             24.ccsp-dmcli                           "
echo "====================================================="

echo "=================================================================="
echo " usage:sh /lib/rdk/CMF_bulid_ccsp_devscript.sh CCSP_Component_Name"
echo "==================================================================="


workspace_location="/build-qemux86broadband/source/"
mkdir -p $workspace_location
cd $workspace_location

execute_component $1 
